# Generated by Django 5.0.6 on 2024-05-31 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="is_correct",
        ),
    ]
